name: Adopter
description: Create a request for adding your company to the adopters page
body:
  - type: input
    id: company
    attributes:
      label: |
        Please provide the name of your company with an optional and very short (max. 5 words) description or slogan.
        For example, "Super Duper Corp, your consultancy buddy"
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: |
        Provide an optional URL to link to. The link will be used on the company name and logo.
    validations:
      required: false
  - type: input
    id: logo
    attributes:
      label: |
        Provide an URL to your company logo. It will be part of the adopters list.
        Please use a logo that works well on white background (check the existing adopters list).
    validations:
      required: true
  - type: textarea
    id: testimonial
    attributes:
      label: |
        Please provide a short testimonial describing how and why Kluctl solves something for you.
        Check the existing list of adopters for real world examples.
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: |
        What is your name and title at your company? This will be shown in the adopters section.
        Example: "John Doe, CTO at Super Duper Corp."
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: |
        Optionally describe what your company does and maybe how you found out about Kluctl.
        This will not be part of the adopters list, but helps us a lot to understand where adopters come from and why
        they ended up using Kluctl.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: authorization
      description: By submitting this request, you agree that you are authorized to add the company to this page and that we can use your logo.
      options:
        - label: I agree to the statement above.
          required: true
